import type { Metadata } from 'next'
import '../styles/globals.css'
import { MarketingHeader } from '@/app/(marketing)/_components/marketing-header'
import { fontsVariables } from '@/lib/fonts'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${fontsVariables} dark font-sans antialiased`}>
                {children}
            </body>
        </html>
    )
}
