import type { Metadata } from 'next'
import '../styles/globals.css'
import { MarketingHeader } from '@/app/(marketing)/components/marketing-header'
import { fontsVariables } from '@/lib/fonts'
import { Providers } from '@/components/providers/providers'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${fontsVariables} font-sans antialiased`}>
                <div className="relative flex min-h-svh flex-col">
                    <Providers>{children}</Providers>
                </div>
            </body>
        </html>
    )
}
