import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { SiteHeader } from "@/components/site-header";

const fontsans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontmono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontsans.variable} ${fontmono.variable} antialiased dark font-sans relative`}
      >
        <SiteHeader />
        {children}

        <Image
          src="/background.png"
          alt="Background Image"
          fill
          className="object-cover -z-10 blur-md"
        />
      </body>
    </html>
  );
}
